# Generated by Django 5.2.8 on 2025-12-24 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=108)),
                ('lastname', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=180)),
                ('status', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField()),
                ('updated_date', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
        ),
    ]
