# Generated by Django 5.2.8 on 2026-02-03 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_booking_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Head_office',
        ),
    ]
