# Generated by Django 5.2.8 on 2026-02-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_rename_admin_head_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head_office',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
