# Generated by Django 5.2.8 on 2026-02-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_alter_head_office_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=180)),
            ],
        ),
    ]
