# Generated by Django 5.2.8 on 2026-02-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0006_login_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login_details',
            new_name='LoginDetails',
        ),
    ]
