# Generated by Django 5.2.8 on 2026-02-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0007_rename_login_details_logindetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking_details',
        ),
        migrations.DeleteModel(
            name='Head_office',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
