# Generated by Django 5.2.8 on 2026-02-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0008_delete_booking_details_delete_head_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
