# Generated by Django 5.2.8 on 2026-03-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0009_alter_logindetails_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('poster', models.URLField()),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
