# Generated by Django 5.2.8 on 2026-03-03 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0012_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('total_tickets', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(max_length=50)),
                ('booking_status', models.CharField(default='CONFIRMED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.logindetails')),
            ],
        ),
    ]
