# Generated by Django 5.2.8 on 2026-03-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0013_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='user_details.booking')),
            ],
        ),
    ]
