# Generated by Django 5.2.8 on 2026-03-03 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0014_bookedseat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.logindetails')),
            ],
        ),
    ]
