# Generated by Django 5.2.8 on 2026-03-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0016_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tittle',
            new_name='title',
        ),
    ]
